after_success: |
  if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
    echo "$PGP_SECRET" | base64 --decode | gpg --import
    if [ -z "$TRAVIS_TAG" ]; then
        sbt publishSigned
    else
        sbt publishSigned sonatypeRelease
    fi
  fi
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
deploy:
  api_key:
    secure: d1BWiZHzV0WrTVZfg4ZJrw/8+RTdpYbLZ7O1WsgN3EWKg4qy9XYI9wP7R4m66cr04de0HrLDMHC+/ZkjI+1g+ibISMGKxji62cG9CobW67cgpSfGFm8EcPZNoQyxJRC0MwgTYi756Q1LAGs1FCo1smcEGjuYodQMLSywNZnJMstIUJzbjjysGShufzwwAPnT339CkNbqmXQrbkJv6qWec/SzJxnn/pftrCwRFBDTA4z2mOVmTSfK/+EGLxmVdqIOTKTCL+x+y+QZlSiP2W16HHS4jNDp7QKCPP0REnMjrftiMMkqOo+IEOCvTlK1WRH/SjaxiRcVWSxKfWb4H2XV1SoxKqkgNvLz1S0cBVcQFcnWDqtsj5l70lfiriDir326IIkYfSrTk0+J9hStfyQzICzjHnfN3YQ0kBtqcApY9wpkr9jhrdQsFeTZwp7zBKAvp2qe08ou8Y9K+oPTW0F0QZwrCVf9/PqSeUqMV2uMO7nuLxrbn+qXTcXVx5oG7+TmmbE1txKu9rZJ6LyxKe4yefEaULL3TlodZyLoFqUxY6oyP9P7gvktTVUwp51Tv8KkuSQeBrQuowiU70QE83WL2r94XygD7cLXUjGAbDPp/kDTeI5iA4Qrma1v2pyWxp38Cu2Zo/ylsB8ZtaqdhDojmB6E0fiClXGmJV8L9gozEhc=
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk: openjdk8
language: scala
script:
- '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
- sbt package
